# ========== Application Config ==========
base.url=https://demowebshop.tricentis.com/register
#app.url.staging=https://demowebshop.tricentis.com/register

# ========== Browser Config ==========
browser=chrome

headless=true
implicit.wait=10
explicit.wait=20
page.load.timeout=30

valid.username=standard_user
valid.password=secret_sauce
locked.username=locked_out_user

# ========== Screenshot Config ==========
screenshot.path=screenshots/
screenshot.on.failure=true

# ========== Report Config ==========
report.path=reports/
report.name=TestExecutionReport
